sudo: false
language: node_js
node_js:
    - "8"
cache:
    directories:
        - "build"
        - "node_modules"
env:
    global:
        secure: "HSK2sIUNiEnUStV1OD+LsTxsTax/86DEou2m/G+SCMTVDtflGcadr7rjHfIaCs1s/Njrlz1T4VvMvtYQ4I8FyzoeSI+tMQ/0n2PJwxUTfqZ4DKDCsZ8uNIiz5H+9U8M87iPP9p8jIYnJli34utriJNwDbwzmu70XphTLk1kKoO4SBgnFL+fP+CJs/aIeCYPL7p4TazqgaWcBcDiWpwPQJKngjewj+LWzIOjz0emmYbyqgmnjjt1y2SjmpJctkIkLU/wlHO6esNMhn5Y2SmsdiMSbpDojxN2OyVaz2iIRB1+BXImxiGElQs4F42eqFMzjHJ2N/e76qL4hsdKy3b1hLcFe2oRQuExksDAUKDGo6p2WDUJGzZDazbnqnffeqIzTwPHdu66z7jmvTukyJ5vYBMZw2LhroPHkv8lvwcTEQtMSZO13CCg95oNPi4Tz7hmcD5DTaq/YxrNXwlqWUBf+Jo/hmwvfawHjOckOyirRvDJ0GtPTBsD/2m2TkuTXYsXogR0HsgRPSnsH/91WSwksZNVmAFqHaZrvih+q9R+BBlrb9MdxkKITNvSPM38fiDCSo93EG/ICaZMp/q4Vy5gTzHVzgJohbU/INByXMO+Bo8aGNI3+37CXorjo8JQo6YXh3z0X+96Cyv9ulkAOeveBSPWcUUJ7J9E1c56stXqGpUc="
    matrix:
        - FX_VERSION="54.0"
        - FX_VERSION="52.0.3"
matrix:
    fast_finish: true
    #allow_failures:
    #    - env: FX_CHANNEL="beta"
notifications:
    email: false
addons:
  apt:
    packages:
    - dbus-x11
install:
    - if [ $FX_VERSION = "52.0.3" ]; then
        wget -O tarball "https://archive.mozilla.org/pub/firefox/tinderbox-builds/mozilla-release-linux64-add-on-devel/1491732920/firefox-52.0.3.en-US.linux-x86_64-add-on-devel.tar.bz2";
      fi
    - if [ $FX_VERSION = "54.0" ]; then
        wget -O tarball "https://archive.mozilla.org/pub/firefox/tinderbox-builds/mozilla-release-linux64-add-on-devel/1496944705/firefox-54.0.en-US.linux-x86_64-add-on-devel.tar.bz2";
      fi
    - tar xf tarball
before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - npm i
    - npm run build
    - if [ $FX_VERSION = "54.0" ] &&
         [ $TRAVIS_REPO_SLUG = "jurism/zotero" ] &&
         [ $TRAVIS_BRANCH = "jurism-5.0" ] &&
         [ $TRAVIS_PULL_REQUEST = "false" ]; then
        mkdir build-zip;
        cd build;
        zip -r ../build-zip/$TRAVIS_COMMIT.zip *;
        cd ..;
        gem install dpl;
        dpl --provider=s3
            --access-key-id=AKIAJAFHAHA64NF66VKQ
            --bucket=jurism-download
            --local-dir=build-zip
            --upload-dir=ci/client
            --acl=public-read
            --skip_cleanup=true;
      fi
    - unset AWS_SECRET_ACCESS_KEY
    # Fix warnings in output
    - dbus-launch
script:
    - test/runtests.sh -x firefox/firefox -f
