sudo: false
language: node_js
node_js:
    - "8"
cache:
    directories:
        - "build"
        - "node_modules"
env:
    global:
        - secure: vTNJuwd99Fufe/oJsHPgey7WcX0loxYN59grpUAruQYoOGIMdaIBmSUKaYnsvvgvKkYfcAH0tLbFJsvE6XvJbCvV+y3XOHqhAjVxS7Rrt1biD+VPUWoeZQQLOOTUEgyq/SXw76kirE/woKCnAtOCFYUnEyYPgSrBnK131iAG2z92K9xrJ53JmUKo40r1N7O/siSvh/6im5sjGyTlA9TgWt21V0RB1BfQ2e5VkJCCMyVf8VL7lZ0zeVi4FfmvY8llwDroECa43DEoSZYpKUT4x3Wc5EfF7YC8TFTmNYqhMYtujs0fEl39gC4D2rdwA8meNwXwL70GmMI4jQTG2Bk9PJILzCKGZdNuStDPSyI7zgQWGGqD9eyy7lTHimMjPvOalD48xWfqNpu7UMaz63bF5rksuFiuPMSjPQiPtFvmswJRFlTT5uvd64XmJuZMS9ob6dDrHJPytC5zrBp2Mkx34neqCE6pkRkZ02Qq90u9iIrDaYfwZzguDoM+I8P+knU5U4fHuQkG41z9nTxh5YnZBj0G6tw4Tz5nh2Hk2DQfmB2lvXAEhc//TTkZbebqc6BQNuH1vHzDMIxzFaEuv9j6SSAWC0wbRX7qk7mddwMWiZTjoAc7sBCocC6Eo1jf5i3fwgXBDuI5YvtGCtdsLBnLWcWCyeWoIGz66Z8X3z4hfm4=
        - secure: KLQdJSqlyveM586oPEu8AV3iQXcIecTb22PuoLZdcM3kTIlWtii30HSPdELxMAVNzgdtWsPmy098TW4lkq7QXqvhSLAwHHP5PP+XU94oJyn8z9ytsQzeIXm5c2hRIdkX2Tl8F7XNynzVqXWmG6NlhSlA2r6vR4zLwxB7d17/4nSbDZwLRW90+E1rW1B51DHCtoFYKC8eM7Pa18+Tyxi9l8X7UUvBzlHxjkKc6Rucj/a2mtPLOjTJhQcGISpqY6i/iCDWo+b+ovZSbNgsHGbEoyj24KihOVC6DwuJD8MNTQgBq9OobrhsUVhsL3vZOzWawvWAotE6zHq5k/E4u9F+ZFDvc1PqnmzO35u2LhSO4ls7rSsBqlgyD5qtcAjb4zZh3kx3qvogXyoVf4uExMFeyTSJcdd5dkPyqny1Q+wAYp9Kxe/SXG7E8ydC9LbFCXtYy/LHyoqTYnL6bn+ND6XT1ZBbjcZDmY0yGnnqI4Jg17Fq8ideDuFMchbiKtzFUxuXt5b6gL+lnkFrEXeWwKby6hTpUg6E9XO+UDi2rmrfqPbZdv+LjaJiV9gyx5oqAXoH05ohIeaJegVuBZIM8N+zHmOdcMLt/pZT25KqOdqQzdblRhMT6jlqVb2sSLKODrXh6Uln5BYhWwM8wUvz8EE/qaJcjibvWBEW81nusosyDXc=
    matrix:
        - FX_VERSION="54.0"
        - FX_VERSION="52.0.3"
matrix:
    fast_finish: true
    #allow_failures:
    #    - env: FX_CHANNEL="beta"
notifications:
    email: false
addons:
  apt:
    packages:
    - dbus-x11
install:
    - if [ $FX_VERSION = "52.0.3" ]; then
        wget -O tarball "https://archive.mozilla.org/pub/firefox/tinderbox-builds/mozilla-release-linux64-add-on-devel/1491732920/firefox-52.0.3.en-US.linux-x86_64-add-on-devel.tar.bz2";
      fi
    - if [ $FX_VERSION = "54.0" ]; then
        wget -O tarball "https://archive.mozilla.org/pub/firefox/tinderbox-builds/mozilla-release-linux64-add-on-devel/1496944705/firefox-54.0.en-US.linux-x86_64-add-on-devel.tar.bz2";
      fi
    - tar xf tarball
before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - npm i
    - npm run build
    - if [ $FX_VERSION = "54.0" ] &&
         [ $TRAVIS_REPO_SLUG = "Juris-M/zotero" ] &&
         [ $TRAVIS_BRANCH = "jurism-5.0" ] &&
         [ $TRAVIS_PULL_REQUEST = "false" ]; then
        mkdir build-zip;
        cd build;
        sed -si "s/%%VALUE%%/${CL_KEY}/" "resource/config.js"
        zip -r ../build-zip/$TRAVIS_COMMIT.zip *;
        cd ..;
        gem install dpl;
        dpl --provider=s3
            --access-key-id=AKIAJAFHAHA64NF66VKQ
            --bucket=jurism-download
            --local-dir=build-zip
            --upload-dir=ci/client
            --acl=public-read
            --skip_cleanup=true;
      fi
    - unset AWS_SECRET_ACCESS_KEY
    # Fix warnings in output
    - dbus-launch
script:
    - test/runtests.sh -x firefox/firefox -f
